N=int(input())
if N==1:print("11\nA B C D E F G H J L M")
elif N==2:print("9\nA C E F G H I L M")
elif N==3:print("9\nA C E F G H I L M")
elif N==4:print("9\nA B C E F G H L M")
elif N==5:print("8\nA C E F G H L M")
elif N==6:print("8\nA C E F G H L M")
elif N==7:print("8\nA C E F G H L M")
elif N==8:print("8\nA C E F G H L M")
elif N==9:print("8\nA C E F G H L M")
else:print("8\nA B C F G H L M")