import sys
input = sys.stdin.readline

N=int(input())
for i in range(N):print(" @@@   @@@  ",end='')
print()
for i in range(N):print("@   @ @   @ ",end='')
print()
for i in range(N):print("@    @    @ ",end='')
print()
for i in range(N):print("@         @ ",end='')
print()
for i in range(N):print(" @       @  ",end='')
print()
for i in range(N):print("  @     @   ",end='')
print()
for i in range(N):print("   @   @    ",end='')
print()
for i in range(N):print("    @ @     ",end='')
print()
for i in range(N):print("     @      ",end='')